# Generated by Django 4.1.5 on 2023-02-20 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_logo_alter_category_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='logo_author',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='logo_big',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 31, 49, 588732)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 31, 49, 620010)),
        ),
    ]
