# Generated by Django 4.1.5 on 2023-02-20 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutcompany_logo_author_aboutcompany_logo_big_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='name',
            new_name='name_author',
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='name_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 34, 25, 388220)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 34, 25, 419472)),
        ),
    ]
