# Generated by Django 4.1.5 on 2023-02-20 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_aboutcompany_name_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 38, 4, 385163)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 38, 4, 434508)),
        ),
    ]
