# Generated by Django 4.1.5 on 2023-02-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teacher_assistant_alter_category_posted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='offline_online',
            new_name='type_course',
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 59, 3, 546961)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 59, 3, 609472)),
        ),
    ]
