# Generated by Django 4.1.5 on 2023-02-21 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_posted_date_alter_news_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 20, 50, 4, 928133)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 20, 50, 4, 981124)),
        ),
    ]
