# Generated by Django 4.1.5 on 2023-02-21 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sendmessage_text_alter_category_posted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageForTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('text', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 23, 24, 40, 422959)),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 23, 24, 40, 485459)),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
